[global]
port = 3001

[development]
address = "0.0.0.0"
keep_alive = 5
log = "normal"

[staging]
address = "0.0.0.0"
keep_alive = 5
log = "normal"

[production]
address = "0.0.0.0"
keep_alive = 5
log = "critical"
